'use client'
import { calculatePayoffSchedule } from '@/lib/debt-optimizer/engine'
import type { Loan, PayoffStrategy } from '@/lib/debt-optimizer/types'
import { ArrowRight, Check, Landmark, LockKeyhole, Plus, RefreshCw, ShieldCheck, Sparkles, TrendingDown, WalletCards, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'

type Lang='en'|'sv'
const C={
 en:{tabs:['Today','Compare','Refinance'],title:'Stop paying interest. Start building freedom.',sub:'See your exact debt-free date and saved interest. Local. Private. Free.',start:'Build my plan',demo:'View example',private:'Your data never leaves this device',plan:'Your plan',hint:'Tune the numbers. We’ll handle the math.',add:'Add debt',balance:'Balance',rate:'Interest',payment:'Monthly payment',extra:'Extra monthly',free:'DEBT-FREE',earlier:'earlier',saved:'Interest saved',reinvest:'Reinvest freed payments',total:'Total debt',monthly:'Monthly outflow',reset:'Reset plan'},
 sv:{tabs:['Idag','Jämför','Omfinansiera'],title:'Sluta betala ränta. Börja bygga frihet.',sub:'Se exakt när du blir skuldfri och hur mycket ränta du sparar. Lokalt. Privat. Gratis.',start:'Bygg min plan',demo:'Se exempel',private:'Din data lämnar aldrig den här enheten',plan:'Din plan',hint:'Justera siffrorna. Vi sköter matematiken.',add:'Lägg till skuld',balance:'Saldo',rate:'Ränta',payment:'Månadsbetalning',extra:'Extra per månad',free:'SKULDFRI',earlier:'tidigare',saved:'Sparad ränta',reinvest:'Återinvestera frigjorda betalningar',total:'Total skuld',monthly:'Per månad',reset:'Nollställ plan'}
} as const
const demo:Loan[]=[
 {id:'mortgage',name:'Mortgage',loanType:'Rak amortering',paymentStyle:'fixed_amort',balance:2000000,interestRate:.041,currentMonthlyPayment:8400,extraMonthly:2500,extraMonthlyEnabled:true,extraMonthlyFrom:'2026-08'},
 {id:'personal',name:'Personal loan',loanType:'Annuitet',paymentStyle:'annuity',balance:180000,interestRate:.115,currentMonthlyPayment:3900,extraMonthly:1800,extraMonthlyEnabled:true,extraMonthlyFrom:'2026-08'}]
const money=(n:number,l:Lang,compact=false)=>new Intl.NumberFormat(l==='sv'?'sv-SE':'en-US',{style:'currency',currency:'SEK',maximumFractionDigits:0,notation:compact?'compact':'standard'}).format(n)
const date=(s:string,l:Lang)=>{if(!s||s==='-')return '—';const[y,m]=s.split('-').map(Number);return new Intl.DateTimeFormat(l==='sv'?'sv-SE':'en-US',{month:'short',year:'numeric'}).format(new Date(y,m-1))}
const span=(n:number,l:Lang)=>`${Math.floor(n/12)}${l==='sv'?' år ':'y '}${n%12}${l==='sv'?' mån':'m'}`
function Count({n,l}:{n:number,l:Lang}){const[v,setV]=useState(0);useEffect(()=>{let f=0,s=performance.now();const go=(x:number)=>{const p=Math.min((x-s)/900,1);setV(Math.round(n*(1-(1-p)**3)));if(p<1)f=requestAnimationFrame(go)};f=requestAnimationFrame(go);return()=>cancelAnimationFrame(f)},[n]);return <>{money(v,l,true)}</>}

export default function Page(){
 const[lang,setLang]=useState<Lang>('en'),[tab,setTab]=useState(0),[loans,setLoans]=useState<Loan[]>([]),[strategy,setStrategy]=useState<PayoffStrategy>('avalanche'),[reinvest,setReinvest]=useState(true)
 useEffect(()=>{const x=localStorage.getItem('debtkill-lang');if(x==='en'||x==='sv')setLang(x)},[])
 const t=C[lang],result=useMemo(()=>loans.length?calculatePayoffSchedule({loans:loans.map((x,i)=>({...x,reinvestment:i&&reinvest?{enabled:true,fromLoanId:loans[0].id,amount:loans[0].currentMonthlyPayment+(loans[0].extraMonthly||0),startDate:'2026-08'}:undefined})),oneTimePayments:[],startDate:'2026-08',strategy}):null,[loans,strategy,reinvest])
 const setL=(l:Lang)=>{setLang(l);localStorage.setItem('debtkill-lang',l)},update=(id:string,k:keyof Loan,v:number)=>setLoans(a=>a.map(x=>x.id===id?{...x,[k]:v}:x)),total=loans.reduce((a,x)=>a+x.balance,0),monthly=loans.reduce((a,x)=>a+x.currentMonthlyPayment+(x.extraMonthly||0),0)
 const add=()=>setLoans(a=>[...a,{id:String(Date.now()),name:`Debt ${a.length+1}`,loanType:'Annuitet',paymentStyle:'annuity',balance:100000,interestRate:.069,currentMonthlyPayment:2500,extraMonthly:500,extraMonthlyEnabled:true,extraMonthlyFrom:'2026-08'}])
 return <div className="min-h-screen bg-[#06060A] text-white selection:bg-blue-500/30">
  <header className="sticky top-0 z-50 border-b border-white/[.06] bg-[#06060A]/80 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-[1480px] items-center justify-between px-5 md:px-10"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-[10px] bg-gradient-to-br from-blue-400 to-blue-700"><TrendingDown size={18}/></span><b>DebtKill</b><span className="rounded-full border border-blue-400/20 bg-blue-500/10 px-2 py-1 text-[9px] font-bold tracking-widest text-blue-300">PRO</span></div><nav className="absolute left-1/2 hidden -translate-x-1/2 rounded-full border border-white/[.06] bg-white/[.025] p-1 md:flex">{t.tabs.map((x,i)=><button onClick={()=>setTab(i)} className={`rounded-full px-5 py-2 text-xs ${tab===i?'bg-white/10':'text-white/35'}`} key={x}>{x}</button>)}</nav><div className="rounded-full border border-white/[.07] p-1 text-[11px] font-semibold">{(['en','sv'] as Lang[]).map(x=><button key={x} onClick={()=>setL(x)} className={`rounded-full px-3 py-1.5 ${lang===x?'bg-white/10':'text-white/30'}`}>{x.toUpperCase()}</button>)}</div></div></header>
  {!loans.length?<main className="mx-auto max-w-[1400px] px-5 py-10 md:px-10"><section className="relative flex min-h-[500px] overflow-hidden rounded-[32px] border border-white/[.06] bg-[#101015] px-7 py-12 md:px-16"><div className="absolute left-[62%] top-1/2 h-72 w-72 -translate-y-1/2 rounded-full bg-gradient-to-br from-blue-500/50 via-violet-500/30 to-cyan-400/30 blur-[60px] animate-pulse"/><div className="relative z-10 grid w-full items-center gap-12 lg:grid-cols-[1.15fr_.85fr]"><div><div className="mb-5 flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-blue-400"><Sparkles size={14}/>Your fastest path to zero</div><h1 className="max-w-3xl text-[42px] font-semibold leading-[1.02] tracking-[-.05em] md:text-[56px]">{t.title}</h1><p className="mt-6 max-w-xl text-lg leading-7 text-white/45">{t.sub}</p><div className="mt-9 flex gap-3"><button onClick={()=>setLoans(demo)} className="flex h-12 items-center gap-2 rounded-full bg-gradient-to-r from-blue-600 to-blue-400 px-6 text-sm font-semibold shadow-[0_0_35px_rgba(59,130,246,.3)]">{t.start}<ArrowRight size={16}/></button><button onClick={()=>setLoans(demo)} className="rounded-full border border-white/10 bg-white/[.035] px-6 text-sm">{t.demo}</button></div><div className="mt-6 flex gap-2 text-xs text-white/30"><LockKeyhole size={13}/>{t.private}</div></div><div className="relative mx-auto h-72 w-full max-w-sm"><div className="absolute left-1/2 top-1/2 h-56 w-56 -translate-x-1/2 -translate-y-1/2 rotate-[-12deg] rounded-full border border-white/10 bg-white/[.04] p-7 shadow-2xl backdrop-blur-2xl"><div className="h-full rounded-full bg-[conic-gradient(#3B82F6_0_72%,#22D3A7_72%_90%,rgba(255,255,255,.08)_90%)] p-8"><div className="grid h-full place-items-center rounded-full bg-[#09090e] text-xl font-bold">2.18M</div></div></div><Preview c="bottom-0 left-0 -rotate-3" name="Mortgage" val="2,000,000 kr" icon={<Landmark size={15}/>} /><Preview c="right-0 top-0 rotate-3" name="Personal" val="180,000 kr" icon={<WalletCards size={15}/>} /></div></div></section></main>:
  <main className="mx-auto grid max-w-[1480px] gap-6 px-5 py-10 md:px-10 lg:grid-cols-[1fr_390px]"><section><div className="mb-7 flex items-end justify-between"><div><span className="text-xs font-bold uppercase tracking-widest text-blue-400">{t.tabs[tab]}</span><h1 className="mt-2 text-4xl font-semibold tracking-[-.04em]">{t.plan}</h1><p className="mt-2 text-sm text-white/35">{t.hint}</p></div><button onClick={add} className="flex gap-2 rounded-full border border-white/10 px-4 py-2 text-xs"><Plus size={14}/>{t.add}</button></div><div className="mb-4 grid grid-cols-2 gap-3"><Stat l={t.total} v={money(total,lang,true)}/><Stat l={t.monthly} v={money(monthly,lang)}/></div><div className="space-y-3">{loans.map((x,i)=><article key={x.id} className="rounded-[24px] border border-white/[.06] bg-[#101015] p-6"><div className="mb-5 flex justify-between"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-500/10 text-blue-400">{i?<WalletCards size={18}/>:<Landmark size={18}/>}</span><input value={x.name} onChange={e=>setLoans(a=>a.map(y=>y.id===x.id?{...y,name:e.target.value}:y))} className="bg-transparent font-semibold outline-none"/></div><button onClick={()=>setLoans(a=>a.filter(y=>y.id!==x.id))}><X size={15} className="text-white/25"/></button></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[t.balance,'balance',x.balance,1],[t.rate,'interestRate',x.interestRate*100,.01],[t.payment,'currentMonthlyPayment',x.currentMonthlyPayment,1],[t.extra,'extraMonthly',x.extraMonthly||0,1]].map(([l,k,v,step])=><label key={String(k)} className="rounded-2xl border border-white/[.06] bg-black/10 p-3"><small className="block uppercase tracking-wider text-white/25">{l}</small><input type="number" step={step} value={v} onChange={e=>update(x.id,k as keyof Loan,Number(e.target.value)*(k==='interestRate'?.01:1))} className="mt-1 w-full bg-transparent outline-none"/></label>)}</div></article>)}</div><div className="mt-5 flex gap-2">{(['avalanche','snowball','custom'] as PayoffStrategy[]).map(x=><button onClick={()=>setStrategy(x)} key={x} className={`rounded-full border px-4 py-2 text-xs capitalize ${strategy===x?'border-blue-400/30 bg-blue-500/10 text-blue-300':'border-white/[.06] text-white/35'}`}>{x}</button>)}<button onClick={()=>setLoans([])} className="ml-auto flex gap-2 p-2 text-xs text-white/30"><RefreshCw size={13}/>{t.reset}</button></div></section>
  <aside className="space-y-4 lg:sticky lg:top-24 lg:h-fit"><div className="min-h-[180px] rounded-[24px] border border-blue-400/20 bg-gradient-to-br from-blue-500/[.16] to-[#101015] p-6"><div className="flex justify-between text-[10px] font-bold tracking-[.18em] text-blue-300">{t.free}<ShieldCheck size={17}/></div><div className="mt-6 text-[56px] font-semibold leading-none tracking-[-.06em]">{date(result?.newFreedomDate||'-',lang)}</div><span className="mt-4 inline-flex rounded-full bg-emerald-400/10 px-3 py-1.5 text-xs font-semibold text-emerald-300">{span(result?.totalMonthsSaved||0,lang)} {t.earlier}</span></div><div className="rounded-[24px] border border-white/[.06] bg-[#101015] p-6"><span className="text-sm text-white/40">{t.saved}</span><div className="mt-4 text-4xl font-semibold"><Count n={Math.max(0,result?.totalInterestSaved||0)} l={lang}/></div></div><button onClick={()=>setReinvest(!reinvest)} className={`flex w-full items-center justify-between rounded-[24px] border p-5 ${reinvest?'border-blue-400/20 bg-blue-500/[.08]':'border-white/[.06] bg-[#101015]'}`}><span className="text-sm">{t.reinvest}</span><span className={`relative h-7 w-12 rounded-full ${reinvest?'bg-blue-500 shadow-[0_0_20px_#3b82f688]':'bg-white/10'}`}><i className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${reinvest?'left-6':'left-1'}`}/></span></button><div className="rounded-[24px] border border-white/[.06] bg-[#101015] p-5">{result?.loanResults.map(x=><div key={x.id} className="flex items-center gap-3 border-b border-white/[.05] py-3 last:border-0"><span className="grid h-6 w-6 place-items-center rounded-full bg-white/5 text-xs">{x.payoffOrder}</span><span className="flex-1 text-xs">{x.name}</span><span className="flex gap-1 text-xs text-emerald-400"><Check size={12}/>{date(x.newEndDate,lang)}</span></div>)}</div></aside></main>}
 </div>
}
function Preview({c,name,val,icon}:{c:string,name:string,val:string,icon:React.ReactNode}){return <div className={`absolute w-52 rounded-2xl border border-white/10 bg-white/[.07] p-4 shadow-2xl backdrop-blur-xl ${c}`}><div className="flex justify-between text-xs text-white/45">{name}{icon}</div><b className="mt-2 block text-lg">{val}</b></div>}
function Stat({l,v}:{l:string,v:string}){return <div className="rounded-2xl border border-white/[.06] bg-[#101015] p-4"><small className="uppercase tracking-wider text-white/25">{l}</small><b className="mt-2 block text-lg">{v}</b></div>}
